# Generated by Django 5.2.6 on 2025-09-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='familymember',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='familymember',
            name='relationship',
            field=models.CharField(blank=True, default='', help_text='Parentesco (ej. Esposo/a, Hijo/a)', max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, help_text='Raza (ej. Labrador)', max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.CharField(blank=True, help_text='Especie (ej. Perro, Gato)', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(blank=True, help_text='Marca (ej. Toyota)', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, help_text='Modelo (ej. Corolla)', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(default='', help_text='Placa del vehículo', max_length=20),
        ),
    ]
