# Generated by Django 5.2.6 on 2025-09-27 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_familymember_full_name_familymember_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-publish_date']},
        ),
        migrations.RemoveField(
            model_name='notice',
            name='published_at',
        ),
        migrations.AddField(
            model_name='notice',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
