# Generated by Django 5.2.6 on 2025-09-27 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_notice_options_remove_notice_published_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#888888', help_text='Color en formato hexadecimal, ej. #FF5733', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='core.noticecategory'),
        ),
    ]
