# Generated by Django 5.2.6 on 2025-09-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
    ]
