# Generated by Django 5.2.6 on 2025-09-28 12:58

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_maintenancerequest_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=core.models.maintenance_attachment_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.maintenancerequest')),
            ],
        ),
    ]
