# Generated by Django 5.2.6 on 2025-09-29 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aplica_alicuota', models.BooleanField(default=True)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cuotas',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('piso', models.CharField(blank=True, max_length=50, null=True)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('alicuota', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'unidades',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('es_propietario', models.BooleanField(default=True)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residentes', to='condominio.unidad')),
            ],
            options={
                'db_table': 'residentes',
                'indexes': [models.Index(fields=['unidad'], name='residentes_unidad__349e17_idx')],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('tipo', models.CharField(choices=[('cargo', 'cargo'), ('pago', 'pago')], max_length=5)),
                ('concepto', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('medio_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='condominio.unidad')),
            ],
            options={
                'db_table': 'movimientos',
                'indexes': [models.Index(fields=['unidad', 'periodo'], name='movimientos_unidad__2d522b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('tipo', 'cargo')), fields=('unidad', 'periodo', 'concepto'), name='uniq_cargo_mes')],
            },
        ),
    ]
